# Generated by Django 5.1.4 on 2024-12-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('holiday_date', models.DateField()),
                ('country', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
